//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrolled
    {
        public int EnrolledID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Names { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string Title { get; set; }
        public string Img { get; set; }
        public string Desriptions { get; set; }
        public string Content { get; set; }
        public string Category { get; set; }
        public Nullable<int> Fee { get; set; }
        public string CourseStatus { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual SignUp SignUp { get; set; }
    }
}
